### PR TITLE
V1.2 list tasks

### LINKED ISSUE #11: As a user, I can view all tasks

### PR DESCRIPTION
**Pull request by beetee17**
### Changes

- Add command to list all tasks: ListTasksCommand
- Add the ability to filter the task list with a predicate 
- Update GUI to show split pane that shows the filtered task list on the left and the filtered person list on the right
- Add tests for new classes.

Closes #11

### CODE REVIEW

**Review by kianseong — COMMENTED** [review]
Code looks clean and organised. JavaDocs well formatted as well.

The next step would be to add more tests (can check coverage in IntelliJ) to ensure our numbers don't drop. 

Other than that, LGTM 👍

**Review by amresh2000 — DISMISSED** [review]
LGTM

**Review by amresh2000 — APPROVED** [review]
LGTM

**Comment by beetee17** [comment]
Added more tests to increase coverage. Unfortunately, this PR consists of a significant amount of UI related code, which causes the code coverage to be misrepresentative of the actual coverage.

**Review by kianseong — APPROVED** [review]

**Pull request merged**
